# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sqk7e0chBetQ3PUPmvpSydA30TJWsJ-Q
"""

import pandas as pd
import numpy as np
import os
import joblib

MODEL_DIR = "../models"
os.makedirs(MODEL_DIR, exist_ok=True)

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("../dataset/resume_data_last_dance.csv")

df.columns = (
    df.columns
      .str.strip()
      .str.replace('\ufeff', '', regex=False)
)

print(df.columns.tolist())

features = [
    "career_objective",
    "skills",
    "educational_institution_name",
    "degree_names",
    "educational_results",
    "result_types",
    "major_field_of_studies",
    "related_skils_in_job",
    "positions",
    "responsibilities",
    "extra_curricular_activity_types",
    "role_positions",
    "languages",
    "proficiency_levels",
    "certification_providers",
    "certification_skills",
    "job_position_name",
    "educationaL_requirements",
    "experiencere_requirement",
    "age_requirement",
    "responsibilities.1",
    "skills_required",
]

target = "matched_score"

# Keep only required columns
df = df[features + [target]].copy()

# Fill missing values
# NOTE: use pd.api.types.is_numeric_dtype() instead of `dtype == "object"`.
# Newer pandas versions can read text columns in as "string" dtype (not
# "object"), which would otherwise fall through to the numeric branch and
# crash on .median().
for col in df.columns:
    if pd.api.types.is_numeric_dtype(df[col]):
        df[col] = df[col].fillna(df[col].median())
    else:
        df[col] = df[col].fillna("Unknown")

# Features and target
X = df[features]
y = df[target]

missing = [col for col in features + [target] if col not in df.columns]
print("Missing columns:", missing)

pd.set_option('display.max_columns', None)
print(df.head())

import numpy as np

# Replace common missing value strings with actual NaN
df.replace(
    ["N/A", "NA", "None", "none", "null", "NULL", "", "nan"],
    np.nan,
    inplace=True
)

# Also replace strings like "['N/A']" or "['N/A', 'N/A']"
df = df.replace(r".*N/A.*", np.nan, regex=True)

# Fill missing values
for col in df.columns:
    if pd.api.types.is_numeric_dtype(df[col]):
        df[col] = df[col].fillna(df[col].median())
    else:
        df[col] = df[col].fillna("Unknown")

print(df.isnull().sum())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer

# All columns are text except numeric ones
numeric_cols = [c for c in X.columns if pd.api.types.is_numeric_dtype(X[c])]
categorical_cols = [c for c in X.columns if c not in numeric_cols]

# Numeric preprocessing
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# TF-IDF for each text column
transformers = []

# Numeric columns
if len(numeric_cols) > 0:
    transformers.append(("num", numeric_transformer, numeric_cols))

# TF-IDF for every text column
for col in categorical_cols:
    transformers.append(
        (
            col,
            Pipeline([
                ("imputer", SimpleImputer(strategy="constant", fill_value="")),
                ("tfidf", TfidfVectorizer(max_features=500))
            ]),
            [col]
        )
    )

preprocessor = ColumnTransformer(transformers)

# Combine all text columns into one
X = df[features].copy()

categorical_cols = [c for c in X.columns if not pd.api.types.is_numeric_dtype(X[c])]
X["text"] = X[categorical_cols].fillna("").agg(" ".join, axis=1)

X = X[["text"] + numeric_cols]

# Create one text column
text_columns = [c for c in X.columns if not pd.api.types.is_numeric_dtype(X[c])]

X["text"] = (
    X[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

X = X[["text"]]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(type(X_train))
print(X_train.shape)
print(X_train.head())

print(type(preprocessor))
print(preprocessor)

from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import FunctionTransformer
from sklearn.pipeline import Pipeline

text_pipeline = Pipeline([
    ("flatten", FunctionTransformer(lambda x: x.squeeze(), validate=False)),
    ("tfidf", TfidfVectorizer(
        max_features=10000,
        ngram_range=(1,2),
        stop_words="english",
        sublinear_tf=True
    ))
])

preprocessor = ColumnTransformer([
    ("text", text_pipeline, ["text"])
])

from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

preprocessor = ColumnTransformer([
    ("text", TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 3),
    min_df=2,
    max_df=0.9,
    sublinear_tf=True,
    stop_words="english"
)),
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]), numeric_cols)
])

from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import loguniform
from sklearn.feature_extraction.text import TfidfVectorizer

svr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,
        ngram_range=(1,2),
        stop_words="english",
        sublinear_tf=True
    )),
    ("model", SVR(
        kernel="rbf",
        C=10,
        gamma="scale",
        epsilon=0.05
    ))
])

svr_pipeline.fit(X_train["text"], y_train)

# Evaluation
y_pred = svr_pipeline.predict(X_test["text"])

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("SVR Results")
print(f"MAE : {mae:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"R2  : {r2:.4f}")

svr_model_path = os.path.join(MODEL_DIR, "svr_model.joblib")
joblib.dump(svr_pipeline, svr_model_path)
print(f"Saved SVR pipeline to {svr_model_path}")

'''
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from catboost import CatBoostRegressor

cat_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,
        ngram_range=(1,2),
        stop_words="english"
    )),
    ("model", CatBoostRegressor(
        iterations=500,
        learning_rate=0.05,
        depth=8,
        loss_function="RMSE",
        verbose=0,
        random_state=42
    ))
])

cat_pipeline.fit(X_train["text"], y_train)

y_pred = cat_pipeline.predict(X_test["text"])

# Evaluation
print("CatBoost Results")
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2  :", r2_score(y_test, y_pred))

cat_model_path = os.path.join(MODEL_DIR, "catboost_model.joblib")
joblib.dump(cat_pipeline, cat_model_path)
print(f"Saved CatBoost pipeline to {cat_model_path}")

'''

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Random Forest Pipeline
rf_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,
        ngram_range=(1,2),
        stop_words="english",
        sublinear_tf=True
    )),
    ("model", RandomForestRegressor(
        n_estimators=300,
        max_depth=30,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    ))
])

param_dist = {
    "model__n_estimators": [200, 300, 500],
    "model__max_depth": [20, 30, 40, None],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__max_features": ["sqrt", "log2"]
}

# Train
rf_pipeline.fit(X_train["text"], y_train)

# Predict
y_pred = rf_pipeline.predict(X_test["text"])

# Evaluation
print("Random Forest Results")
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2  :", r2_score(y_test, y_pred))

rf_model_path = os.path.join(MODEL_DIR, "random_forest_model.joblib")
joblib.dump(rf_pipeline, rf_model_path)
print(f"Saved Random Forest pipeline to {rf_model_path}")

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# XGBoost Pipeline
xgb_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,
        ngram_range=(1,2),
        stop_words="english",
        sublinear_tf=True
    )),
    ("model", XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=8,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42
    ))
])

param_dist = {
    "model__n_estimators": [300, 500, 700],
    "model__max_depth": [4, 6, 8, 10],
    "model__learning_rate": [0.01, 0.03, 0.05, 0.1],
    "model__subsample": [0.7, 0.8, 1.0],
    "model__colsample_bytree": [0.7, 0.8, 1.0]
}

# Train
xgb_pipeline.fit(X_train["text"], y_train)

# Predict
y_pred = xgb_pipeline.predict(X_test["text"])

# Evaluation
print("XGBoost Results")
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2  :", r2_score(y_test, y_pred))

xgb_model_path = os.path.join(MODEL_DIR, "xgboost_model.joblib")
joblib.dump(xgb_pipeline, xgb_model_path)
print(f"Saved XGBoost pipeline to {xgb_model_path}")